<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
   
   <joint name="camera_joint" type="fixed">
      <origin xyz="${-0.121 + 0.180 + 0.345 - 0.02} 0.0 ${chassis_height + head_height - 0.048}" rpy="0.0 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="camera_link"/>
   </joint>

   <link name="camera_link">
      <visual>
         <geometry>
            <mesh filename="package://arns_description/meshes/camera.stl" scale="0.001 0.001 0.001"/>
         </geometry>
      </visual>
      <collision>
         <origin xyz="-0.02 0.0 0.0" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="0.04 0.120 0.04"/>
         </geometry>
      </collision>
      <xacro:inertial_box mass="0.01" x="0.04" y="0.120" z="0.04">
         <origin xyz="-0.02 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <joint name="camera_joint_optical" type="fixed">
      <origin xyz="0.0 0.0 0.0" rpy="-${pi/2} 0.0 -${pi/2}"/>
      <parent link="camera_link"/>
      <child link="camera_link_optical"/>
   </joint>

   <link name="camera_link_optical"></link>

   <gazebo reference="camera_link">
      <material>Gazebo/Red</material>
      <sensor name="camera" type="camera">
         <visualize>true</visualize>
         <update_rate>30.0</update_rate>
         <camera>
            <horizontal_fov>1.5708</horizontal_fov>
            <image>
               <format>R8G8B8</format>
               <width>640</width>
               <height>480</height>
            </image>
            <clip>
               <near>0.05</near>
               <far>8.0</far>
            </clip>
         </camera>
         <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <frame_name>camera_link_optical</frame_name>
         </plugin>
      </sensor>
   </gazebo>

</robot>