<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


   <joint name="lidar_joint" type="fixed">
      <parent link="lidar_case_link"/>
      <child link="lidar_link"/>
      <origin xyz="0 0 ${lidar_height}" rpy="0 0 0"/>
      <axis xyz="0 0 0"/>
   </joint>

   <link name="lidar_link">
      <visual>
         <origin xyz="0 0 -${lidar_height/2}"/>
         <geometry>
            <mesh filename="file://$(find arns_description)/meshes/lidar.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <origin xyz="0 0 -${lidar_height/2}"/>
         <geometry>
            <cylinder radius="0.037" length="0.021"/>
         </geometry>
         <material name="black"/>
      </collision>
      <xacro:inertial_cylinder mass="0.07" length="0.021" radius="0.037">
            <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <gazebo reference="lidar_link">
      <material>Gazebo/Black</material>
      <sensor name="laser" type="ray">
         <pose>0 0 0 0 0 0</pose>
         <visualize>false</visualize>
         <update_rate>10</update_rate>
         <ray>
            <scan>
               <horizontal>
                  <sample>360</sample>
                  <min_angle>-3.14</min_angle>
                  <max_angle>3.14</max_angle>
               </horizontal>
            </scan>
            <range>
               <min>0.3</min>
               <max>12</max>
            </range>
         </ray>
         <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
            <ros>
               <remapping>~/out:=scan</remapping>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <frame_name>lidar_link</frame_name>
         </plugin>
      </sensor>
   </gazebo>

</robot>
