<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <link name="base_link">
      <visual>
         <origin xyz="-0.121 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <mesh filename="package://arns_description/meshes/chassis.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
         <origin xyz="${(chassis_length/2)-0.121} 0.0 ${chassis_height/2}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
         </geometry>
      </collision>

      <visual name="head_floor1_visual">
         <origin xyz="0.150 0.0 ${chassis_height - 0.020}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <mesh filename="package://arns_description/meshes/head_floor.stl" scale="0.001 0.001 0.001"/>
         </geometry>
      </visual>
      <collision name="head_floor1_collision">
         <origin xyz="0.150 0.0 ${chassis_height - 0.015}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="0.150 0.260 0.020"/>
         </geometry>
      </collision>

      <visual name="head_floor2_visual">
         <origin xyz="0.3 0.0 ${chassis_height - 0.020}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <mesh filename="package://arns_description/meshes/head_floor.stl" scale="0.001 0.001 0.001"/>
         </geometry>
      </visual>
      <collision name="head_floor2_collision">
         <origin xyz="0.3 0.0 ${chassis_height - 0.015}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="0.150 0.260 0.020"/>
         </geometry>
      </collision>

      <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
         <origin xyz="${(chassis_length/2)-0.121} 0.0 ${chassis_height/2}" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>
   
   <link name="base_footprint">
   </link>

   <!-- CHASSIS -->

   <joint name="base_joint" type="fixed">
      <origin xyz="0 0 ${wheel_z_offset + wheel_radius}" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
   </joint>

   <!-- HEAD -->

   <joint name="head_joint" type="fixed">
      <origin xyz="${-0.121 + 0.180 + (0.345/2) - 0.005} 0.0 ${chassis_height - 0.0134}" rpy="0.0 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="head_link"/>
   </joint>

   <link name="head_link">
      <visual>
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi/2}"/>
         <geometry>
            <mesh filename="package://arns_description/meshes/head.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="white"/>
      </visual>
      <collision>
         <origin xyz="0.005 0 ${(head_height/2) + 0.005}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="${head_length + 0.040} ${head_width} ${head_height}"/>
         </geometry>
      </collision>

      <xacro:inertial_box mass="${head_mass}" x="${head_width}" y="${head_length}" z="${head_height}">
         <origin xyz="${0.005} 0.0 ${(head_height/2) + 0.005}" rpy="0.0 0.0 ${pi/2}"/>
      </xacro:inertial_box>
   </link>

   <!-- LIDAR CASE -->

   <joint name="lidar_case_joint" type="fixed">
      <origin xyz="-0.07 0.0 ${head_height + 0.005}" rpy="0.0 0.0 0.0"/>
      <parent link="head_link"/>
      <child link="lidar_case_link"/>
   </joint>

   <link name="lidar_case_link">
      <visual>
         <geometry>
            <mesh filename="package://arns_description/meshes/lidar_case.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="lightblue"/>
      </visual>
      <collision>
         <origin xyz="-0.001 0.0 ${(lidar_case_height/2)}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="${lidar_case_length} ${lidar_case_width} ${lidar_case_height}"/>
         </geometry>
      </collision>
      <xacro:inertial_box mass="0.01" x="${lidar_case_length}" y="${lidar_case_width}" z="${lidar_case_height}">
         <origin xyz="-0.001 0.0 ${(lidar_case_height/2)}" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <!-- SCREEN CASE -->

   <joint name="screen_case_joint" type="fixed">
      <origin xyz="0.07 0.0 ${head_height + 0.005}" rpy="0.0 0.0 0.0"/>
      <parent link="head_link"/>
      <child link="screen_case_link"/>
   </joint>

   <link name="screen_case_link">
      <visual>
         <geometry>
            <mesh filename="package://arns_description/meshes/screen_case.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="lightblue"/>
      </visual>
      <collision>
         <origin xyz="0.0 0.0 ${screen_case_height/2}" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="${screen_case_length} ${screen_case_width} ${screen_case_height}"/>
         </geometry>
      </collision>
      <xacro:inertial_box mass="0.01" x="${screen_case_length}" y="${screen_case_width}" z="${screen_case_height}">
         <origin xyz="0.0 0.0 ${screen_case_height/2}" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <!-- SCREEN -->

   <joint name="screen_joint" type="fixed">
      <origin xyz="0.07 0.0 ${head_height + screen_case_height + 0.005}" rpy="0.0 0.0 0.0"/>
      <parent link="head_link"/>
      <child link="screen_link"/>
      
   </joint>

   <link name="screen_link">
      <visual>
         <geometry>
            <mesh filename="package://arns_description/meshes/screen.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
         <geometry>
            <box size="${screen_length} ${screen_width} ${screen_height}"/>
         </geometry>
      </collision>
      <xacro:inertial_box mass="0.01" x="${screen_length}" y="${screen_width}" z="${screen_height}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <!-- LEFT WHEEL-->

   <joint name="left_wheel_joint" type="continuous">
      <origin xyz="0.0 ${wheel_y_offset} -${wheel_z_offset}" rpy="-${pi/2} 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="left_wheel_link"/>
      <axis xyz="0.0 0.0 1"/>
      <dynamics damping="0.7" friction="0.1" />
   </joint>

   <link name="left_wheel_link">
      <visual>
         <origin xyz="0.0 0.0 0.0" rpy="-${pi/2} 0.0 0.0"/>
         <geometry>
            <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}"/> -->
            <mesh filename="package://arns_description/meshes/left_wheel.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
         <geometry>
            <cylinder radius="${wheel_radius + 0.002}" length="${wheel_length}"/>
         </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_cylinder>
   </link>

   <!-- RIGHT WHEEL -->

   <joint name="right_wheel_joint" type="continuous">
      <origin xyz="0.0 -${wheel_y_offset} -${wheel_z_offset}" rpy="${pi/2} 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
      <axis xyz="0.0 0.0 -1"/>
      <dynamics damping="0.7" friction="0.1" />
   </joint>

   <link name="right_wheel_link">
      <visual>
         <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
         <geometry>
            <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}"/> -->
            <mesh filename="package://arns_description/meshes/right_wheel.stl" scale="0.001 0.001 0.001"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
         <geometry>
            <cylinder radius="${wheel_radius + 0.002}" length="${wheel_length}"/>
         </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_cylinder>
   </link>
   
   <!-- CASTER WHEEL -->

   <joint name="caster_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_wheel_link"/>
      <origin xyz="${caster_wheel_offset_x - 0.121046} 0 -0.026"/>
   </joint>

   <link name="caster_wheel_link">
      <visual>
         <geometry>
            <sphere radius="${caster_wheel_radius}"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <geometry>
            <sphere radius="${caster_wheel_radius}"/>
         </geometry>

         <!-- <xacro:no_wheel_slipping/> -->
         
      </collision>
      <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_sphere>
   </link>

   <gazebo reference="base_link">
      <material>Gazebo/White</material>
   </gazebo>

   <gazebo reference="head_link">
      <material>Gazebo/White</material>
   </gazebo>

   <gazebo reference="left_wheel_link">
      <material>Gazebo/Black</material>
   </gazebo>

   <gazebo reference="right_wheel_link">
      <material>Gazebo/Black</material>
   </gazebo>

   <gazebo reference="lidar_case_link">
      <material>Gazebo/Blue</material>
   </gazebo>

   <gazebo reference="screen_case_link">
      <material>Gazebo/Blue</material>
   </gazebo>

   <gazebo reference="screen_link">
      <material>Gazebo/Black</material>
   </gazebo>

   <gazebo reference="caster_wheel_link">
      <material>Gazebo/Black</material>
   </gazebo>
   
   <gazebo reference="caster_wheel_link">
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>
   </gazebo>

</robot>